
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 23 16:40:38 BRT 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENTIFIER = 45;
  public static final int CHARACTER_STRING = 46;
  public static final int REAL = 69;
  public static final int GT = 54;
  public static final int PACKED = 28;
  public static final int TYPE = 36;
  public static final int STARSTAR = 65;
  public static final int CONST = 4;
  public static final int GE = 53;
  public static final int UNTIL = 38;
  public static final int ASSIGNMENT = 47;
  public static final int COMMA = 49;
  public static final int RPAREN = 64;
  public static final int LT = 58;
  public static final int INTEGER = 67;
  public static final int LPAREN = 57;
  public static final int FALSE = 72;
  public static final int NOT = 6;
  public static final int LE = 56;
  public static final int NIL = 26;
  public static final int ARRAY = 2;
  public static final int VAR = 40;
  public static final int GOTO = 21;
  public static final int PBEGIN = 60;
  public static final int UPARROW = 66;
  public static final int EXTERNAL = 33;
  public static final int RECORD = 31;
  public static final int MOD = 12;
  public static final int SLASH = 13;
  public static final int TRUE = 71;
  public static final int PLUS = 10;
  public static final int UNIT = 37;
  public static final int EQUAL = 52;
  public static final int IMPLEMENTATION = 22;
  public static final int INTERFACE = 24;
  public static final int CHAR = 70;
  public static final int BOOLEAN = 68;
  public static final int DO = 14;
  public static final int DIGSEQ = 50;
  public static final int FOR = 18;
  public static final int STAR = 9;
  public static final int DIV = 11;
  public static final int DOWNTO = 15;
  public static final int DOTDOT = 51;
  public static final int DOT = 44;
  public static final int PROCEDURE = 29;
  public static final int EOF = 0;
  public static final int SEMICOLON = 43;
  public static final int FUNCTION = 20;
  public static final int LABEL = 25;
  public static final int MINUS = 8;
  public static final int IN = 23;
  public static final int OR = 7;
  public static final int SET = 32;
  public static final int error = 1;
  public static final int PFILE = 61;
  public static final int RBRAC = 62;
  public static final int OF = 27;
  public static final int END = 16;
  public static final int COLON = 48;
  public static final int FILE = 17;
  public static final int NOTEQUAL = 59;
  public static final int BEGIN = 3;
  public static final int FORWARD = 19;
  public static final int STRING = 34;
  public static final int LBRAC = 55;
  public static final int PROGRAM = 30;
  public static final int AND = 5;
  public static final int TO = 35;
  public static final int REALNUMBER = 63;
  public static final int WITH = 41;
  public static final int USES = 39;
  public static final int XOR = 42;
}

